try to turn off canary test and see if there is any timeout

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -121,15 +121,15 @@ pytorch_linux_test_defaults: &pytorch_linux_test_defaults
         # =================== The following code will be executed inside Docker container ===================
         set -ex
 
-        # Canary Test 1: Timeout on TestNN
-        if [[ "${CIRCLE_JOB}" == *test* ]] && [[ "${CIRCLE_JOB}" != *cuda* ]]; then
-          # This test normally takes 8 seconds. On a bad machine it can take >20 minutes.
-          # Here we give it 30 seconds to run.
-          timeout 30 python test/test_nn.py -v TestNN.test_BatchNorm3d || \
-            (echo "This machine is unhealthy. Re-running this job on another machine." && \
-            curl -X POST https://circleci.com/api/v1.1/project/github/pytorch/pytorch/${CIRCLE_BUILD_NUM}/retry?circle-token=${CIRCLECI_TOKEN} && \
-            exit 1)
-        fi
+        # # Canary Test 1: Timeout on TestNN
+        # if [[ "${CIRCLE_JOB}" == *test* ]] && [[ "${CIRCLE_JOB}" != *cuda* ]]; then
+        #   # This test normally takes 8 seconds. On a bad machine it can take >20 minutes.
+        #   # Here we give it 30 seconds to run.
+        #   timeout 30 python test/test_nn.py -v TestNN.test_BatchNorm3d || \
+        #     (echo "This machine is unhealthy. Re-running this job on another machine." && \
+        #     curl -X POST https://circleci.com/api/v1.1/project/github/pytorch/pytorch/${CIRCLE_BUILD_NUM}/retry?circle-token=${CIRCLECI_TOKEN} && \
+        #     exit 1)
+        # fi
 
         if [ -n "${MULTI_GPU}" ]; then
           ./.jenkins/pytorch/multigpu-test.sh
