add env setup steps

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -67,6 +67,50 @@ linux_build_defaults: &linux_build_defaults
         # Reinitialize submodules
         git submodule sync && git submodule update --init --recursive
 
+        TOP_DIR="$PWD"
+        OS="$(uname)"
+
+        compilers=(
+            cc
+            c++
+            gcc
+            g++
+            x86_64-linux-gnu-gcc
+        )
+
+        # setup ccache
+        if [[ "$OS" == "Darwin" ]]; then
+            export PATH="/usr/local/opt/ccache/libexec:$PATH"
+        else
+            if ! hash sccache 2>/dev/null; then
+                echo "SCCACHE_BUCKET is set but sccache executable is not found"
+                exit 1
+            fi
+            SCCACHE_BIN_DIR="$TOP_DIR/sccache"
+            mkdir -p "$SCCACHE_BIN_DIR"
+            for compiler in "${compilers[@]}"; do
+                (
+                    echo "#!/bin/sh"
+                    echo "exec $(which sccache) $(which $compiler) \\\"\\\$@\\\""
+                ) > "$SCCACHE_BIN_DIR/$compiler"
+                chmod +x "$SCCACHE_BIN_DIR/$compiler"
+            done
+            export PATH="$SCCACHE_BIN_DIR:$PATH"
+        fi
+
+        # setup virtualenv
+        VENV_DIR=/tmp/venv
+
+        PYTHON="$(which python)"
+        if [[ "${BUILD_ENVIRONMENT}" =~ py((2|3)\\.?[0-9]?\\.?[0-9]?) ]]; then
+            PYTHON=$(which "python${BASH_REMATCH[1]}")
+        fi
+
+        $PYTHON -m virtualenv "$VENV_DIR"
+
+        source "$VENV_DIR/bin/activate"
+        pip install -U pip setuptools
+
         # TODO: add onnx build steps
         ./scripts/onnx/install-develop.sh
 
@@ -141,6 +185,10 @@ linux_test_defaults: &linux_test_defaults
         cat >/home/circleci/project/ci_test_script.sh <<EOL
         # =================== The following code will be executed inside Docker container ===================
         set -ex
+
+        # setup virtualenv
+        VENV_DIR=/tmp/venv
+        source "$VENV_DIR/bin/activate"
 
         #TODO: add onnx test steps here
         ./scripts/onnx/test.sh
