.circleci: Only do comparisons when available
Comparisons were being done on branches where the '<<
pipeline.git.base_revision >>' didn't exist before so let's just move it
so that comparison / code branch is only run when that variable is
available

Signed-off-by: Eli Uriegas <eliuriegas@fb.com>

[ghstack-poisoned]

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -2050,7 +2050,6 @@ jobs:
               export AWS_SECRET_ACCESS_KEY=${CIRCLECI_AWS_SECRET_KEY_FOR_DOCKER_BUILDER_V1}
               eval $(aws ecr get-login --no-include-email --region us-east-1)
               set -x
-              PREVIOUS_DOCKER_TAG=$(git rev-parse "$(git merge-base HEAD << pipeline.git.base_revision >>):.circleci/docker")
               # Check if image already exists, if it does then skip building it
               if docker manifest inspect "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/${IMAGE_NAME}:${DOCKER_TAG}"; then
                 circleci-agent step halt
@@ -2058,11 +2057,14 @@ jobs:
                 # explicitly exit the step here ourselves before it causes too much trouble
                 exit 0
               fi
-              # If no image exists but the hash is the same as the previous hash then we should error out here
-              if [[ ${PREVIOUS_DOCKER_TAG} = ${DOCKER_TAG} ]]; then
-                echo "ERROR: Something has gone wrong and the previous image isn't available for the merge-base of your branch"
-                echo "       contact the PyTorch team to restore the original images"
-                exit 1
+              if [[ -n "<< pipeline.git.base_revision >>" ]]; then
+                PREVIOUS_DOCKER_TAG=$(git rev-parse "$(git merge-base HEAD << pipeline.git.base_revision >>):.circleci/docker")
+                # If no image exists but the hash is the same as the previous hash then we should error out here
+                if [[ ${PREVIOUS_DOCKER_TAG} = ${DOCKER_TAG} ]]; then
+                  echo "ERROR: Something has gone wrong and the previous image isn't available for the merge-base of your branch"
+                  echo "       contact the PyTorch team to restore the original images"
+                  exit 1
+                fi
               fi
         - run:
             name: build_docker_image_<< parameters.image_name >>
