Update on ".circleci: Only do comparisons when available"
Comparisons were being done on branches where the '<<
pipeline.git.base_revision >>' didn't exist before so let's just move it
so that comparison / code branch is only run when that variable is
available

Example: https://app.circleci.com/pipelines/github/pytorch/pytorch/198611/workflows/8a316eef-d864-4bb0-863f-1454696b1e8a/jobs/6610393

Signed-off-by: Eli Uriegas <eliuriegas@fb.com>

Differential Revision: [D23032900](https://our.internmc.facebook.com/intern/diff/D23032900)

[ghstack-poisoned]

diff --git a/.circleci/verbatim-sources/job-specs/docker_jobs.yml b/.circleci/verbatim-sources/job-specs/docker_jobs.yml
--- a/.circleci/verbatim-sources/job-specs/docker_jobs.yml
+++ b/.circleci/verbatim-sources/job-specs/docker_jobs.yml
@@ -32,11 +32,12 @@
               # Covers the case where a previous tag doesn't exist for the tree
               # this is only really applicable on trees that don't have `.circleci/docker` at its merge base, i.e. nightly
               if ! git rev-parse "$(git merge-base HEAD << pipeline.git.base_revision >>):.circleci/docker"; then
-                exit 0
+                echo "Directory '.circleci/docker' not found in tree << pipeline.git.base_revision >>, you should probably rebase onto a more recent commit"
+                exit 1
               fi
-              PREVIOUS_TAG=$(git rev-parse "$(git merge-base HEAD << pipeline.git.base_revision >>):.circleci/docker")
+              PREVIOUS_DOCKER_TAG=$(git rev-parse "$(git merge-base HEAD << pipeline.git.base_revision >>):.circleci/docker")
               # If no image exists but the hash is the same as the previous hash then we should error out here
-              if [[ "${PREVIOUS_TAG}" = "${DOCKER_TAG}" ]]; then
+              if [[ "${PREVIOUS_DOCKER_TAG}" = "${DOCKER_TAG}" ]]; then
                 echo "ERROR: Something has gone wrong and the previous image isn't available for the merge-base of your branch"
                 echo "       contact the PyTorch team to restore the original images"
                 exit 1
