DO NOT MERGE, rebuilding android image
Signed-off-by: Eli Uriegas <eliuriegas@fb.com>

[ghstack-poisoned]

diff --git a/.circleci/verbatim-sources/job-specs/docker_jobs.yml b/.circleci/verbatim-sources/job-specs/docker_jobs.yml
--- a/.circleci/verbatim-sources/job-specs/docker_jobs.yml
+++ b/.circleci/verbatim-sources/job-specs/docker_jobs.yml
@@ -35,13 +35,13 @@
                 echo "Directory '.circleci/docker' not found in tree << pipeline.git.base_revision >>, you should probably rebase onto a more recent commit"
                 exit 1
               fi
-              PREVIOUS_DOCKER_TAG=$(git rev-parse "$(git merge-base HEAD << pipeline.git.base_revision >>):.circleci/docker")
-              # If no image exists but the hash is the same as the previous hash then we should error out here
-              if [[ "${PREVIOUS_DOCKER_TAG}" = "${DOCKER_TAG}" ]]; then
-                echo "ERROR: Something has gone wrong and the previous image isn't available for the merge-base of your branch"
-                echo "       contact the PyTorch team to restore the original images"
-                exit 1
-              fi
+              # PREVIOUS_DOCKER_TAG=$(git rev-parse "$(git merge-base HEAD << pipeline.git.base_revision >>):.circleci/docker")
+              # # If no image exists but the hash is the same as the previous hash then we should error out here
+              # if [[ "${PREVIOUS_DOCKER_TAG}" = "${DOCKER_TAG}" ]]; then
+              #   echo "ERROR: Something has gone wrong and the previous image isn't available for the merge-base of your branch"
+              #   echo "       contact the PyTorch team to restore the original images"
+              #   exit 1
+              # fi
         - run:
             name: build_docker_image_<< parameters.image_name >>
             no_output_timeout: "1h"
