Update on "[CI][IOS] Add lite interpreter ios build job"
## Summary 
As title, add libtorch (lite) in ios x86 Em and

## Test plan
In `config.yml`, remove `context: org-member`:
```
      - pytorch_ios_build:
          build_environment: pytorch-ios-12.0.0-arm64_lite_interpreter_build
          context: org-member
          ios_arch: arm64
          ios_platform: OS
          lite_interpreter: "1"
          name: pytorch_ios_12_0_0_arm64_lite_interpreter_build
```
The build is:

https://app.circleci.com/pipelines/github/pytorch/pytorch/276113/workflows/49fa2f6e-c978-424b-9177-bbe313955876/jobs/11050851

**Build** step finishes successfully:
![image](https://user-images.githubusercontent.com/16430979/108619899-d183b080-73dc-11eb-809d-a21f811cf821.png)

It fails **Run Build Test** because of missing `IOS_DEV_TEAM_ID`




[ghstack-poisoned]

diff --git a/.circleci/verbatim-sources/job-specs/job-specs-custom.yml b/.circleci/verbatim-sources/job-specs/job-specs-custom.yml
--- a/.circleci/verbatim-sources/job-specs/job-specs-custom.yml
+++ b/.circleci/verbatim-sources/job-specs/job-specs-custom.yml
@@ -490,6 +490,52 @@
               export USE_PYTORCH_METAL=${USE_METAL}
             fi
             unbuffer ${PROJ_ROOT}/scripts/build_ios.sh 2>&1 | ts
+      - run:
+          name: Run Build Test
+          no_output_timeout: "30m"
+          command: |
+            set -e
+            if [ ${BUILD_LITE_INTERPRETER} == 1 ]; then
+              echo "not SIMULATOR build, skip it."
+              exit 0
+            fi
+            PROJ_ROOT=/Users/distiller/project
+            PROFILE=PyTorch_CI_2021
+            # run the ruby build script
+            if ! [ -x "$(command -v xcodebuild)" ]; then
+              echo 'Error: xcodebuild is not installed.'
+              exit 1
+            fi
+            echo ${IOS_DEV_TEAM_ID}
+            if [ ${IOS_PLATFORM} != "SIMULATOR" ]; then
+              ruby ${PROJ_ROOT}/scripts/xcode_build.rb -i ${PROJ_ROOT}/build_ios/install -x ${PROJ_ROOT}/ios/TestApp/TestApp.xcodeproj -p ${IOS_PLATFORM} -c ${PROFILE} -t ${IOS_DEV_TEAM_ID}
+            else
+              ruby ${PROJ_ROOT}/scripts/xcode_build.rb -i ${PROJ_ROOT}/build_ios/install -x ${PROJ_ROOT}/ios/TestApp/TestApp.xcodeproj -p ${IOS_PLATFORM}
+            fi
+            if ! [ "$?" -eq "0" ]; then
+              echo 'xcodebuild failed!'
+              exit 1
+            fi
+      - run:
+          name: Run Simulator Tests
+          no_output_timeout: "2h"
+          command: |
+            set -e
+            if [ ${IOS_PLATFORM} != "SIMULATOR" ]; then
+              echo "not SIMULATOR build, skip it."
+              exit 0
+            fi
+            WORKSPACE=/Users/distiller/workspace
+            PROJ_ROOT=/Users/distiller/project
+            source ~/anaconda/bin/activate
+            pip install torch torchvision --progress-bar off
+            #run unit test
+            cd ${PROJ_ROOT}/ios/TestApp/benchmark
+            python trace_model.py
+            ruby setup.rb
+            cd ${PROJ_ROOT}/ios/TestApp
+            instruments -s -devices
+            fastlane scan
   pytorch_linux_bazel_build:
     <<: *pytorch_params
     machine:
