Test Windows container

diff --git a/.circleci/verbatim-sources/job-specs/pytorch-job-specs.yml b/.circleci/verbatim-sources/job-specs/pytorch-job-specs.yml
--- a/.circleci/verbatim-sources/job-specs/pytorch-job-specs.yml
+++ b/.circleci/verbatim-sources/job-specs/pytorch-job-specs.yml
@@ -259,28 +259,49 @@ jobs:
     steps:
       - checkout
       - run:
-          name: Install Cuda
-          no_output_timeout: 30m
-          command: |
-            if [[ "${USE_CUDA}" == "1" ]]; then
-              .circleci/scripts/windows_cuda_install.sh
-            fi
-      - run:
-          name: Install Cudnn
-          command : |
-            if [[ "${USE_CUDA}" == "1" ]]; then
-              .circleci/scripts/windows_cudnn_install.sh
-            fi
-      - run:
           name: Build
           no_output_timeout: "90m"
           command: |
             set -e
+            # No support for CUDA 11 yet
+            if [[ "$CUDA_VERSION" == "11" ]]; then
+              exit 1
+            fi
+
+            # Cleanup disk space
+            rm -rf "C:/ProgramData/Microsoft/VisualStudio/Packages"
+            rm -rf "C:/Program Files (x86)/Microsoft Visual Studio"
+
+            cat > /c/Users/circleci/project/ci_build_script.sh \<<EOL
+            # =================== The following code will be executed inside Docker container ===================
+            set -ex
+            export BUILD_ENVIRONMENT="$BUILD_ENVIRONMENT"
+            export SCCACHE_BUCKET="$SCCACHE_BUCKET"
+            export CUDA_VERSION="$CUDA_VERSION"
+            export PYTHON_VERSION="$PYTHON_VERSION"
+            export VC_VERSION="$VC_VERSION"
+            export VC_YEAR="$VC_YEAR"
+            export VC_PRODUCT="$VC_PRODUCT"
+            export USE_CUDA="$USE_CUDA"
+            export TORCH_CUDA_ARCH_LIST="$TORCH_CUDA_ARCH_LIST"
+
             set +x
             export AWS_ACCESS_KEY_ID=${CIRCLECI_AWS_ACCESS_KEY_FOR_WIN_BUILD_V1}
             export AWS_SECRET_ACCESS_KEY=${CIRCLECI_AWS_SECRET_KEY_FOR_WIN_BUILD_V1}
             set -x
+
+            # Build
+            cd /c/pytorch
             .jenkins/pytorch/win-build.sh
+
+            # =================== The above code will be executed inside Docker container ===================
+            EOL
+            export DOCKER_IMAGE=peterjc123/windows-cuda-container:v3.0.0
+            echo "DOCKER_IMAGE: "${DOCKER_IMAGE}
+            time docker pull ${DOCKER_IMAGE} >/dev/null
+            export id=$(docker run --cap-add=SYS_PTRACE -t -d ${DOCKER_IMAGE})
+            docker cp C:/Users/circleci/project/. $id:C:/pytorch/
+            docker exec -i "$id" sh /c/pytorch/ci_build_script.sh
       - persist_to_workspace:
           root: "C:/w"
           paths: build-results
