comment out prunneccesary cker and killall

diff --git a/.github/actions/setup-rocm/action.yml b/.github/actions/setup-rocm/action.yml
--- a/.github/actions/setup-rocm/action.yml
+++ b/.github/actions/setup-rocm/action.yml
@@ -5,19 +5,19 @@ description: Set up ROCm host for CI
 runs:
   using: composite
   steps:
-    - name: Set DOCKER_HOST
-      shell: bash
-      run: echo "DOCKER_HOST=unix:///run/user/$(id -u)/docker.sock" >> "${GITHUB_ENV}"
+    # - name: Set DOCKER_HOST
+    #   shell: bash
+    #   run: echo "DOCKER_HOST=unix:///run/user/$(id -u)/docker.sock" >> "${GITHUB_ENV}"
 
-    - name: Remove leftover Docker config file
-      shell: bash
-      continue-on-error: true
-      run: |
-        set -ex
+    # - name: Remove leftover Docker config file
+    #   shell: bash
+    #   continue-on-error: true
+    #   run: |
+    #     set -ex
 
-        cat ~/.docker/config.json || true
-        # https://stackoverflow.com/questions/64455468/error-when-logging-into-ecr-with-docker-login-error-saving-credentials-not
-        rm -f ~/.docker/config.json
+    #     cat ~/.docker/config.json || true
+    #     # https://stackoverflow.com/questions/64455468/error-when-logging-into-ecr-with-docker-login-error-saving-credentials-not
+    #     rm -f ~/.docker/config.json
 
     - name: Stop all running docker containers
       if: always()
@@ -73,11 +73,11 @@ runs:
       uses: ./.github/actions/diskspace-cleanup
       if: always()
 
-    - name: Runner health check disconnect on failure
-      if: ${{ failure() }}
-      shell: bash
-      run: |
-        killall runsvc.sh
+    # - name: Runner health check disconnect on failure
+    #   if: ${{ failure() }}
+    #   shell: bash
+    #   run: |
+    #     killall runsvc.sh
 
     - name: Preserve github env variables for use in docker
       shell: bash
