WIP

diff --git a/.github/actions/calculate-docker-image/action.yml b/.github/actions/calculate-docker-image/action.yml
--- a/.github/actions/calculate-docker-image/action.yml
+++ b/.github/actions/calculate-docker-image/action.yml
@@ -72,14 +72,14 @@ runs:
           echo "Directory '.circleci/docker' not found in commit $MERGE_BASE, you should probably rebase onto a more recent commit"
           exit 1
         fi
-        PREVIOUS_DOCKER_TAG=$(git rev-parse "$MERGE_BASE:.circleci/docker")
-        # If no image exists but the hash is the same as the previous hash then we should error out here
-        if [[ "${PREVIOUS_DOCKER_TAG}" = "${DOCKER_TAG}" ]]; then
-          echo "ERROR: Something has gone wrong and the previous image isn't available for the merge-base of your branch"
-          echo "PREVIOUS_DOCKER_TAG ${PREVIOUS_DOCKER_TAG}"
-          echo "       contact the PyTorch team to restore the original images"
-          exit 1
-        fi
+
+        # PREVIOUS_DOCKER_TAG=$(git rev-parse "$MERGE_BASE:.circleci/docker")
+        # # If no image exists but the hash is the same as the previous hash then we should error out here
+        # if [[ "${PREVIOUS_DOCKER_TAG}" = "${DOCKER_TAG}" ]]; then
+        #   echo "ERROR: Something has gone wrong and the previous image isn't available for the merge-base of your branch"
+        #   echo "       contact the PyTorch team to restore the original images"
+        #   exit 1
+        # fi
         echo ::set-output name=rebuild::yes
 
     - name: Build and push docker image
