Workaround container prune for multiple runners on one node

diff --git a/.github/actions/setup-xpu/action.yml b/.github/actions/setup-xpu/action.yml
--- a/.github/actions/setup-xpu/action.yml
+++ b/.github/actions/setup-xpu/action.yml
@@ -10,7 +10,11 @@ runs:
       shell: bash
       run: |
         # Prune all stopped containers.
-        docker container prune -f
+        # If other runner is pruning on this node, will skip.
+        nprune=$(ps -ef | grep -c "docker container prune")
+        if [[ $nprune -eq 1 ]]; then
+          docker container prune -f
+        fi
 
     - name: Runner health check system info
       if: always()
@@ -34,9 +38,9 @@ runs:
         ngpu=$(xpu-smi discovery | grep -c -E 'Device Name')
         msg="Please file an issue on pytorch/pytorch reporting the faulty runner. Include a link to the runner logs so the runner can be identified"
         if [[ $ngpu -eq 0 ]]; then
-            echo "Error: Failed to detect any GPUs on the runner"
-            echo "$msg"
-            exit 1
+          echo "Error: Failed to detect any GPUs on the runner"
+          echo "$msg"
+          exit 1
         fi
 
     - name: Runner diskspace health check
