add GPU_ARCH_TYPE to cuda-aarch64 to install nvidia driver for test

diff --git a/.github/workflows/_binary-build-linux.yml b/.github/workflows/_binary-build-linux.yml
--- a/.github/workflows/_binary-build-linux.yml
+++ b/.github/workflows/_binary-build-linux.yml
@@ -138,154 +138,154 @@ jobs:
         shell: bash
         run: env
 
-      - name: "[FB EMPLOYEES] Enable SSH (Click me for login details)"
-        if: inputs.build_environment != 'linux-s390x-binary-manywheel'
-        uses: pytorch/test-infra/.github/actions/setup-ssh@main
-        continue-on-error: true
-        with:
-          github-secret: ${{ secrets.github-token }}
+      # - name: "[FB EMPLOYEES] Enable SSH (Click me for login details)"
+      #   if: inputs.build_environment != 'linux-s390x-binary-manywheel'
+      #   uses: pytorch/test-infra/.github/actions/setup-ssh@main
+      #   continue-on-error: true
+      #   with:
+      #     github-secret: ${{ secrets.github-token }}
 
-      - name: Checkout PyTorch
-        uses: pytorch/pytorch/.github/actions/checkout-pytorch@main
-        with:
-          no-sudo: ${{ inputs.build_environment == 'linux-aarch64-binary-manywheel' || inputs.build_environment == 'linux-s390x-binary-manywheel' }}
+      # - name: Checkout PyTorch
+      #   uses: pytorch/pytorch/.github/actions/checkout-pytorch@main
+      #   with:
+      #     no-sudo: ${{ inputs.build_environment == 'linux-aarch64-binary-manywheel' || inputs.build_environment == 'linux-s390x-binary-manywheel' }}
 
-      - name: Setup Linux
-        if: inputs.build_environment != 'linux-s390x-binary-manywheel'
-        uses: ./.github/actions/setup-linux
+      # - name: Setup Linux
+      #   if: inputs.build_environment != 'linux-s390x-binary-manywheel'
+      #   uses: ./.github/actions/setup-linux
 
-      - name: Chown workspace
-        if: inputs.build_environment != 'linux-s390x-binary-manywheel'
-        uses: ./.github/actions/chown-workspace
-        with:
-          ALPINE_IMAGE: ${{ inputs.ALPINE_IMAGE }}
+      # - name: Chown workspace
+      #   if: inputs.build_environment != 'linux-s390x-binary-manywheel'
+      #   uses: ./.github/actions/chown-workspace
+      #   with:
+      #     ALPINE_IMAGE: ${{ inputs.ALPINE_IMAGE }}
 
-      - name: Clean workspace
-        shell: bash
-        run: |
-          set -eux
+      # - name: Clean workspace
+      #   shell: bash
+      #   run: |
+      #     set -eux
 
-          rm -rf "${GITHUB_WORKSPACE}"
-          mkdir "${GITHUB_WORKSPACE}"
+      #     rm -rf "${GITHUB_WORKSPACE}"
+      #     mkdir "${GITHUB_WORKSPACE}"
 
-          if [[ ${{ inputs.build_environment }} == 'linux-aarch64-binary-manywheel' ]] || [[ ${{ inputs.build_environment }} == 'linux-s390x-binary-manywheel' ]] ; then
-            rm -rf "${RUNNER_TEMP}/artifacts"
-            mkdir "${RUNNER_TEMP}/artifacts"
-          fi
+      #     if [[ ${{ inputs.build_environment }} == 'linux-aarch64-binary-manywheel' ]] || [[ ${{ inputs.build_environment }} == 'linux-s390x-binary-manywheel' ]] ; then
+      #       rm -rf "${RUNNER_TEMP}/artifacts"
+      #       mkdir "${RUNNER_TEMP}/artifacts"
+      #     fi
 
-      - name: Checkout PyTorch to pytorch dir
-        uses: malfet/checkout@silent-checkout
-        with:
-          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
-          submodules: recursive
-          path: pytorch
-          quiet-checkout: true
+      # - name: Checkout PyTorch to pytorch dir
+      #   uses: malfet/checkout@silent-checkout
+      #   with:
+      #     ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
+      #     submodules: recursive
+      #     path: pytorch
+      #     quiet-checkout: true
 
-      - name: Clean PyTorch checkout
-        run: |
-          # Remove any artifacts from the previous checkouts
-          git clean -fxd
-        working-directory: pytorch
+      # - name: Clean PyTorch checkout
+      #   run: |
+      #     # Remove any artifacts from the previous checkouts
+      #     git clean -fxd
+      #   working-directory: pytorch
 
-      - name: Checkout pytorch/builder to builder dir
-        uses: malfet/checkout@silent-checkout
-        with:
-          ref: set-max-jobs
-          submodules: recursive
-          repository: tinglvv/builder
-          path: builder
-          quiet-checkout: true
+      # - name: Checkout pytorch/builder to builder dir
+      #   uses: malfet/checkout@silent-checkout
+      #   with:
+      #     ref: set-max-jobs
+      #     submodules: recursive
+      #     repository: tinglvv/builder
+      #     path: builder
+      #     quiet-checkout: true
 
-      - name: Clean pytorch/builder checkout
-        run: |
-          # Remove any artifacts from the previous checkouts
-          git clean -fxd
-        working-directory: builder
+      # - name: Clean pytorch/builder checkout
+      #   run: |
+      #     # Remove any artifacts from the previous checkouts
+      #     git clean -fxd
+      #   working-directory: builder
 
-      - name: Check if the job is disabled
-        id: filter
-        uses: ./pytorch/.github/actions/filter-test-configs
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          # NB: Use a mock test matrix with a default value here. After filtering, if the
-          # returned matrix is empty, it means that the job is disabled
-          test-matrix: |
-            { include: [
-              { config: "default" },
-            ]}
+      # - name: Check if the job is disabled
+      #   id: filter
+      #   uses: ./pytorch/.github/actions/filter-test-configs
+      #   with:
+      #     github-token: ${{ secrets.GITHUB_TOKEN }}
+      #     # NB: Use a mock test matrix with a default value here. After filtering, if the
+      #     # returned matrix is empty, it means that the job is disabled
+      #     test-matrix: |
+      #       { include: [
+      #         { config: "default" },
+      #       ]}
 
-      - name: Pull Docker image
-        if: ${{ steps.filter.outputs.is-test-matrix-empty == 'False' && inputs.build_environment != 'linux-s390x-binary-manywheel' }}
-        uses: pytorch/test-infra/.github/actions/pull-docker-image@main
-        with:
-          docker-image: ${{ inputs.DOCKER_IMAGE }}
+      # - name: Pull Docker image
+      #   if: ${{ steps.filter.outputs.is-test-matrix-empty == 'False' && inputs.build_environment != 'linux-s390x-binary-manywheel' }}
+      #   uses: pytorch/test-infra/.github/actions/pull-docker-image@main
+      #   with:
+      #     docker-image: ${{ inputs.DOCKER_IMAGE }}
 
-      - name: Build PyTorch binary
-        if: ${{ steps.filter.outputs.is-test-matrix-empty == 'False' }}
-        run: |
-          set -x
-          mkdir -p artifacts/
-          container_name=$(docker run \
-            -e BINARY_ENV_FILE \
-            -e BUILDER_ROOT \
-            -e BUILD_ENVIRONMENT \
-            -e DESIRED_CUDA \
-            -e DESIRED_DEVTOOLSET \
-            -e DESIRED_PYTHON \
-            -e GITHUB_ACTIONS \
-            -e GPU_ARCH_TYPE \
-            -e GPU_ARCH_VERSION \
-            -e LIBTORCH_VARIANT \
-            -e PACKAGE_TYPE \
-            -e PYTORCH_FINAL_PACKAGE_DIR \
-            -e PYTORCH_ROOT \
-            -e SKIP_ALL_TESTS \
-            -e PYTORCH_EXTRA_INSTALL_REQUIREMENTS \
-            --tty \
-            --detach \
-            -v "${GITHUB_WORKSPACE}/pytorch:/pytorch" \
-            -v "${GITHUB_WORKSPACE}/builder:/builder" \
-            -v "${RUNNER_TEMP}/artifacts:/artifacts" \
-            -w / \
-            "${DOCKER_IMAGE}"
-          )
-          docker exec -t -w "${PYTORCH_ROOT}" "${container_name}" bash -c "bash .circleci/scripts/binary_populate_env.sh"
-          if [[ ${BUILD_ENVIRONMENT} == *"aarch64"* ]]; then
-            docker exec -t "${container_name}" bash -c "bash /builder/aarch64_linux/aarch64_ci_build.sh"
-          else
-            docker exec -t "${container_name}" bash -c "source ${BINARY_ENV_FILE} && bash /builder/${{ inputs.PACKAGE_TYPE }}/build.sh"
-          fi
+      # - name: Build PyTorch binary
+      #   if: ${{ steps.filter.outputs.is-test-matrix-empty == 'False' }}
+      #   run: |
+      #     set -x
+      #     mkdir -p artifacts/
+      #     container_name=$(docker run \
+      #       -e BINARY_ENV_FILE \
+      #       -e BUILDER_ROOT \
+      #       -e BUILD_ENVIRONMENT \
+      #       -e DESIRED_CUDA \
+      #       -e DESIRED_DEVTOOLSET \
+      #       -e DESIRED_PYTHON \
+      #       -e GITHUB_ACTIONS \
+      #       -e GPU_ARCH_TYPE \
+      #       -e GPU_ARCH_VERSION \
+      #       -e LIBTORCH_VARIANT \
+      #       -e PACKAGE_TYPE \
+      #       -e PYTORCH_FINAL_PACKAGE_DIR \
+      #       -e PYTORCH_ROOT \
+      #       -e SKIP_ALL_TESTS \
+      #       -e PYTORCH_EXTRA_INSTALL_REQUIREMENTS \
+      #       --tty \
+      #       --detach \
+      #       -v "${GITHUB_WORKSPACE}/pytorch:/pytorch" \
+      #       -v "${GITHUB_WORKSPACE}/builder:/builder" \
+      #       -v "${RUNNER_TEMP}/artifacts:/artifacts" \
+      #       -w / \
+      #       "${DOCKER_IMAGE}"
+      #     )
+      #     docker exec -t -w "${PYTORCH_ROOT}" "${container_name}" bash -c "bash .circleci/scripts/binary_populate_env.sh"
+      #     if [[ ${BUILD_ENVIRONMENT} == *"aarch64"* ]]; then
+      #       docker exec -t "${container_name}" bash -c "bash /builder/aarch64_linux/aarch64_ci_build.sh"
+      #     else
+      #       docker exec -t "${container_name}" bash -c "source ${BINARY_ENV_FILE} && bash /builder/${{ inputs.PACKAGE_TYPE }}/build.sh"
+      #     fi
 
-      - name: Chown artifacts
-        if: ${{ steps.filter.outputs.is-test-matrix-empty == 'False' && inputs.build_environment != 'linux-s390x-binary-manywheel' }}
-        shell: bash
-        run: |
-          # Ensure the working directory gets chowned back to the current user
-          docker run --rm -v "${RUNNER_TEMP}/artifacts:/v" -w /v "${ALPINE_IMAGE}" chown -R "$(id -u):$(id -g)" .
+      # - name: Chown artifacts
+      #   if: ${{ steps.filter.outputs.is-test-matrix-empty == 'False' && inputs.build_environment != 'linux-s390x-binary-manywheel' }}
+      #   shell: bash
+      #   run: |
+      #     # Ensure the working directory gets chowned back to the current user
+      #     docker run --rm -v "${RUNNER_TEMP}/artifacts:/v" -w /v "${ALPINE_IMAGE}" chown -R "$(id -u):$(id -g)" .
 
-      - uses: actions/upload-artifact@v3
-        if: ${{ steps.filter.outputs.is-test-matrix-empty == 'False' }}
-        with:
-          name: ${{ inputs.build_name }}
-          if-no-files-found: error
-          path:
-            ${{ runner.temp }}/artifacts/*
+      # - uses: actions/upload-artifact@v3
+      #   if: ${{ steps.filter.outputs.is-test-matrix-empty == 'False' }}
+      #   with:
+      #     name: ${{ inputs.build_name }}
+      #     if-no-files-found: error
+      #     path:
+      #       ${{ runner.temp }}/artifacts/*
 
-      - name: Teardown Linux
-        if: always() && inputs.build_environment != 'linux-s390x-binary-manywheel'
-        uses: pytorch/test-infra/.github/actions/teardown-linux@main
+      # - name: Teardown Linux
+      #   if: always() && inputs.build_environment != 'linux-s390x-binary-manywheel'
+      #   uses: pytorch/test-infra/.github/actions/teardown-linux@main
 
-      - name: Chown workspace
-        if: always() && inputs.build_environment != 'linux-s390x-binary-manywheel'
-        uses: ./pytorch/.github/actions/chown-workspace
-        with:
-          ALPINE_IMAGE: ${{ inputs.ALPINE_IMAGE }}
+      # - name: Chown workspace
+      #   if: always() && inputs.build_environment != 'linux-s390x-binary-manywheel'
+      #   uses: ./pytorch/.github/actions/chown-workspace
+      #   with:
+      #     ALPINE_IMAGE: ${{ inputs.ALPINE_IMAGE }}
 
-      - name: Cleanup docker
-        if: always() && inputs.build_environment == 'linux-s390x-binary-manywheel'
-        shell: bash
-        run: |
-          # on s390x stop the container for clean worker stop
-          # ignore expansion of "docker ps -q" since it could be empty
-          # shellcheck disable=SC2046
-          docker stop $(docker ps -q) || true
+      # - name: Cleanup docker
+      #   if: always() && inputs.build_environment == 'linux-s390x-binary-manywheel'
+      #   shell: bash
+      #   run: |
+      #     # on s390x stop the container for clean worker stop
+      #     # ignore expansion of "docker ps -q" since it could be empty
+      #     # shellcheck disable=SC2046
+      #     docker stop $(docker ps -q) || true
