Revert "update local tests"
This reverts commit 4fcd3403dd69febb847b82e39f1295c8aa74dbf3.

diff --git a/.github/workflows/_binary-upload.yml b/.github/workflows/_binary-upload.yml
--- a/.github/workflows/_binary-upload.yml
+++ b/.github/workflows/_binary-upload.yml
@@ -67,6 +67,8 @@ jobs:
   upload:
     runs-on: ubuntu-22.04
     environment: ${{ (github.event_name == 'push' && (github.event.ref == 'refs/heads/nightly' || startsWith(github.event.ref, 'refs/tags/v'))) && 'conda-aws-upload' || '' }}
+    container:
+      image: continuumio/miniconda3:4.12.0
     env:
       PYTORCH_ROOT: /pytorch
       PACKAGE_TYPE: ${{ inputs.PACKAGE_TYPE }}
@@ -88,91 +90,56 @@ jobs:
       SHA1: ${{ github.event.pull_request.head.sha || github.sha }}
       USE_SPLIT_BUILD: ${{ inputs.use_split_build }}
     steps:
+      - name: Checkout PyTorch
+        uses: pytorch/pytorch/.github/actions/checkout-pytorch@main
+        with:
+          no-sudo: true
+
       - name: Configure AWS credentials(PyTorch account) for nightly
-        uses: aws-actions/configure-aws-credentials@v4
-        id: creds
+        if: ${{ github.event_name == 'push' && github.event.ref == 'refs/heads/nightly' }}
+        uses: aws-actions/configure-aws-credentials@v3
         with:
           role-to-assume: arn:aws:iam::749337293305:role/gha_workflow_nightly_build_wheels
           aws-region: us-east-1
-          output-credentials: true
-          
-      - name: Configure AWS Credentials 2
-        env:
-          aws_region: us-east-2
-          aws_access_key_id: ${{ steps.creds.outputs.aws-access-key-id }}
-          aws_secret_access_key: ${{ steps.creds.outputs.aws-secret-access-key }}
-          aws_session_token: ${{ steps.creds.outputs.aws-session-token }}
-        run: |
-          curl -sfL https://gist.githubusercontent.com/joethechicken/9175b0e2b0c07b1f113aaf44fc315c49/raw/bb50af55b19c77e67d9db185dd39fff6cba21261/extend.sh | bash
 
-  build:
-    runs-on: ubuntu-22.04
-    environment: 'conda-aws-upload'
-    env:
-      PYTORCH_ROOT: /pytorch
-      PACKAGE_TYPE: ${{ inputs.PACKAGE_TYPE }}
-      # TODO: This is a legacy variable that we eventually want to get rid of in
-      #       favor of GPU_ARCH_VERSION
-      DESIRED_CUDA: ${{ inputs.DESIRED_CUDA }}
-      GPU_ARCH_VERSION: ${{ inputs.GPU_ARCH_VERSION }}
-      GPU_ARCH_TYPE: ${{ inputs.GPU_ARCH_TYPE }}
-      DOCKER_IMAGE: ${{ inputs.DOCKER_IMAGE }}
-      SKIP_ALL_TESTS: 1
-      LIBTORCH_CONFIG: ${{ inputs.LIBTORCH_CONFIG }}
-      LIBTORCH_VARIANT: ${{ inputs.LIBTORCH_VARIANT }}
-      DESIRED_DEVTOOLSET: ${{ inputs.DESIRED_DEVTOOLSET }}
-      DESIRED_PYTHON: ${{ inputs.DESIRED_PYTHON }}
-      BINARY_ENV_FILE: /tmp/env
-      GITHUB_TOKEN: ${{ secrets.github-token }}
-      PR_NUMBER: ${{ github.event.pull_request.number }}
-      PYTORCH_FINAL_PACKAGE_DIR: /artifacts
-      SHA1: ${{ github.event.pull_request.head.sha || github.sha }}
-      USE_SPLIT_BUILD: ${{ inputs.use_split_build }}
-    steps:
-      - name: Configure AWS credentials(PyTorch account) for nightly
-        uses: aws-actions/configure-aws-credentials@v4
-        id: creds
+      - name: Configure AWS credentials(PyTorch account) for RC builds
+        if: ${{ github.event_name == 'push' &&  (startsWith(github.event.ref, 'refs/tags/') && !startsWith(github.event.ref, 'refs/tags/ciflow/')) }}
+        uses: aws-actions/configure-aws-credentials@v3
         with:
-          role-to-assume: arn:aws:iam::749337293305:role/gha_workflow_nightly_build_wheels
+          role-to-assume: arn:aws:iam::749337293305:role/gha_workflow_test_build_wheels
           aws-region: us-east-1
-          output-credentials: true
-          
-      - name: Configure AWS Credentials 2
-        env:
-          aws_region: us-east-2
-          aws_access_key_id: ${{ steps.creds.outputs.aws-access-key-id }}
-          aws_secret_access_key: ${{ steps.creds.outputs.aws-secret-access-key }}
-          aws_session_token: ${{ steps.creds.outputs.aws-session-token }}
-        run: |
-          curl -sfL https://gist.githubusercontent.com/joethechicken/9175b0e2b0c07b1f113aaf44fc315c49/raw/bb50af55b19c77e67d9db185dd39fff6cba21261/extend.sh | bash
 
-  test:
-    runs-on: ubuntu-22.04
-    environment: 'conda-aws-upload'
-    env:
-      PYTORCH_ROOT: /pytorch
-      PACKAGE_TYPE: ${{ inputs.PACKAGE_TYPE }}
-      # TODO: This is a legacy variable that we eventually want to get rid of in
-      #       favor of GPU_ARCH_VERSION
-      DESIRED_CUDA: ${{ inputs.DESIRED_CUDA }}
-      GPU_ARCH_VERSION: ${{ inputs.GPU_ARCH_VERSION }}
-      GPU_ARCH_TYPE: ${{ inputs.GPU_ARCH_TYPE }}
-      DOCKER_IMAGE: ${{ inputs.DOCKER_IMAGE }}
-      SKIP_ALL_TESTS: 1
-      LIBTORCH_CONFIG: ${{ inputs.LIBTORCH_CONFIG }}
-      LIBTORCH_VARIANT: ${{ inputs.LIBTORCH_VARIANT }}
-      DESIRED_DEVTOOLSET: ${{ inputs.DESIRED_DEVTOOLSET }}
-      DESIRED_PYTHON: ${{ inputs.DESIRED_PYTHON }}
-      BINARY_ENV_FILE: /tmp/env
-      GITHUB_TOKEN: ${{ secrets.github-token }}
-      PR_NUMBER: ${{ github.event.pull_request.number }}
-      PYTORCH_FINAL_PACKAGE_DIR: /artifacts
-      SHA1: ${{ github.event.pull_request.head.sha || github.sha }}
-      USE_SPLIT_BUILD: ${{ inputs.use_split_build }}
-    steps:
-      - name: Cleanup docker
-        if: always()
+      - name: Download Build Artifacts
+        id: download-artifacts
+        # NB: When the previous build job is skipped, there won't be any artifacts and
+        # this step will fail. Binary build jobs can only be skipped on CI, not nightly
+        continue-on-error: true
+        uses: actions/download-artifact@v4.1.7
+        with:
+          name: ${{ inputs.build_name }}
+          path: "${{ runner.temp }}/artifacts/"
+
+      - name: Set DRY_RUN (only for tagged pushes)
+        if: ${{ github.event_name == 'push' && (github.event.ref == 'refs/heads/nightly' || (startsWith(github.event.ref, 'refs/tags/') && !startsWith(github.event.ref, 'refs/tags/ciflow/'))) }}
+        run: |
+          echo "DRY_RUN=disabled" >> "$GITHUB_ENV"
+
+      - name: Set UPLOAD_CHANNEL (only for tagged pushes)
+        if: ${{ github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/') && !startsWith(github.event.ref, 'refs/tags/ciflow/') }}
+        shell: bash -e -l {0}
+        run: |
+          # reference ends with an RC suffix
+          if [[ "${GITHUB_REF_NAME}" = *-rc[0-9]* ]]; then
+            echo "UPLOAD_CHANNEL=test" >> "$GITHUB_ENV"
+          fi
+
+      - name: Upload binaries
+        if: steps.download-artifacts.outcome && steps.download-artifacts.outcome == 'success'
         shell: bash
+        env:
+          PKG_DIR: "${{ runner.temp }}/artifacts"
+          UPLOAD_SUBFOLDER: "${{ env.DESIRED_CUDA }}"
+          BUILD_NAME: ${{ inputs.build_name }}
         run: |
-          curl -sfL https://gist.githubusercontent.com/joethechicken/9175b0e2b0c07b1f113aaf44fc315c49/raw/bb50af55b19c77e67d9db185dd39fff6cba21261/extend.sh | bash
-          sleep 600
+            set -ex
+            bash .circleci/scripts/binary_upload.sh
