Fix conditional git diff in _link_check.yml (#152919)
Pull Request resolved: https://github.com/pytorch/pytorch/pull/152919
Approved by: https://github.com/huydhn

diff --git a/.github/workflows/_link_check.yml b/.github/workflows/_link_check.yml
--- a/.github/workflows/_link_check.yml
+++ b/.github/workflows/_link_check.yml
@@ -1,5 +1,3 @@
-name: Link Checks
-
 on:
   workflow_call:
     inputs:
@@ -23,15 +21,16 @@ jobs:
       ref: ${{ inputs.ref }}
       script: |
         ./scripts/lint_urls.sh $(
-          [ "${{ github.event_name }}" = "pull_request" ] \
-            && git diff --name-only ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }} \
-          || [ "${{ github.event_name }}" = "push" ] \
-            && git diff --name-only ${{ github.event.before }}...${{ github.sha }}
+          { [ "${{ github.event_name }}" = "pull_request" ] \
+              && git diff --name-only "${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }}"; } \
+          || \
+          { [ "${{ github.event_name }}" = "push" ] \
+              && git diff --name-only "${{ github.event.before }}...${{ github.sha }}"; }
         ) || {
           echo
           echo "URL lint failed."
           echo "If this is a transient outage, you can bypass it by adding the \`skip-url-lint\` label to your PR."
-          echo "Or add `@lint-ignore` somewhere on the same line as the URL you want to skip checking."
+          echo "Or add \`@lint-ignore\` somewhere on the same line as the URL you want to skip checking."
           exit 1
         }
 
@@ -47,8 +46,15 @@ jobs:
       ref: ${{ inputs.ref }}
       script: |
         ./scripts/lint_xrefs.sh $(
-          [ "${{ github.event_name }}" = "pull_request" ] \
-            && git diff --name-only ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }} \
-          || [ "${{ github.event_name }}" = "push" ] \
-            && git diff --name-only ${{ github.event.before }}...${{ github.sha }}
-        )
+          { [ "${{ github.event_name }}" = "pull_request" ] \
+              && git diff --name-only "${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }}"; } \
+          || \
+          { [ "${{ github.event_name }}" = "push" ] \
+              && git diff --name-only "${{ github.event.before }}...${{ github.sha }}"; }
+        ) || {
+          echo
+          echo "Xref lint failed."
+          echo "If this is a transient outage, you can bypass it by adding the \`skip-xref-lint\` label to your PR."
+          echo "Or add \`@lint-ignore\` somewhere on the same line as the reference you want to skip checking."
+          exit 1
+        }
