Add Docker error

diff --git a/.github/workflows/_linux-test.yml b/.github/workflows/_linux-test.yml
--- a/.github/workflows/_linux-test.yml
+++ b/.github/workflows/_linux-test.yml
@@ -292,19 +292,32 @@ jobs:
           set +e
           set -x
 
-          # NB: We are currently having an intermittent GPU crashing issue on G5 runners with
+          # NB: We are currently having an intermittent GPU-related issue on G5 runners with
           # A10G GPU. Once this happens, trying to reset the GPU as done in setup-nvidia does
           # not seem to help. Here are some symptoms:
-          #   * Test fails with "No CUDA GPUs are available" error when initialize CUDA
           #   * Calling nvidia-smi timeouts after 60 second
+          #   * Fail to run nvidia-smi with an unable to determine the device handle for GPU
+          #     unknown error
+          #   * Test fails with "No CUDA GPUs are available" error when initialize CUDA
+          #     in PyTorch
+          #   * Run docker --gpus all fails with error response from daemon while the command
+          #     nvidia-container-cli fails with detection error: nvml error: unknown error.
           #
           # As both the root cause and recovery path are unclear, let's take the runner out of
           # service so that it doesn't get any more jobs
-          grep -R -l "No CUDA GPUs are available" "${RUNNER_WORKSPACE}/../../_diag/pages"
-          RC=$?
+          UNRECOVERABLE_ERRORS=(
+            "No CUDA GPUs are available"
+            "docker: Error response from daemon"
+          )
 
-          # If GPU crashes, stop the runner to prevent it from receiving new jobs
-          if [[ "${RC}" == "0" ]]; then
-            echo "The GPU has crashed, shutting down the runner..."
-            .github/scripts/stop_runner_service.sh
-          fi
+          for ERROR in "${UNRECOVERABLE_ERRORS[@]}"
+          do
+            grep -Rli "${ERROR}" "${RUNNER_WORKSPACE}/../../_diag/pages"
+            RC=$?
+
+            # If GPU crashes, stop the runner to prevent it from receiving new jobs
+            if [[ "${RC}" == "0" ]]; then
+              echo "The runner has encoutered an unrecoverable error (${ERROR}), shutting it down..."
+              .github/scripts/stop_runner_service.sh
+            fi
+          done
