Fix a grep-itself bug when checking for GPU healthcheck (#97929)
The logic works https://github.com/pytorch/pytorch/actions/runs/4558327458, but it also grep itself due to `set -x` is set (Ugh, debug message)
Pull Request resolved: https://github.com/pytorch/pytorch/pull/97929
Approved by: https://github.com/malfet, https://github.com/weiwangmeta

diff --git a/.github/workflows/_linux-test.yml b/.github/workflows/_linux-test.yml
--- a/.github/workflows/_linux-test.yml
+++ b/.github/workflows/_linux-test.yml
@@ -272,14 +272,26 @@ jobs:
         uses: pytorch/test-infra/.github/actions/teardown-linux@main
         if: always()
 
+      # NB: We are currently having an intermittent GPU-related issue on G5 runners with
+      # A10G GPU. Once this happens, trying to reset the GPU as done in setup-nvidia does
+      # not seem to help. Here are some symptoms:
+      #   * Calling nvidia-smi timeouts after 60 second
+      #   * Fail to run nvidia-smi with an unable to determine the device handle for GPU
+      #     unknown error
+      #   * Test fails with a missing CUDA GPU error when initializing CUDA in PyTorch
+      #   * Run docker --gpus all fails with error response from daemon
+      #
+      # As both the root cause and recovery path are unclear, let's take the runner out of
+      # service so that it doesn't get any more jobs
       - name: Check NVIDIA driver installation step
-        if: failure() && steps.install-nvidia-driver.conclusion && steps.install-nvidia-driver.conclusion == 'failure'
+        if:
+          failure() &&
+          ((steps.install-nvidia-driver.conclusion && steps.install-nvidia-driver.conclusion == 'failure') || (contains(inputs.build-environment, 'cuda') && !contains(matrix.config, 'nogpu')))
         shell: bash
         env:
           RUNNER_WORKSPACE: ${{ runner.workspace }}
         run: |
           set +e
-          set -x
 
           nvidia-smi
           NVIDIA_SMI_STATUS=$?
@@ -290,30 +302,15 @@ jobs:
             .github/scripts/stop_runner_service.sh
           fi
 
-      - name: Check GPU health (run this last)
+      - name: Check other unrecoverable error (Run this last)
         if: failure() && contains(inputs.build-environment, 'cuda') && !contains(matrix.config, 'nogpu')
         shell: bash
         env:
           RUNNER_WORKSPACE: ${{ runner.workspace }}
         run: |
           set +e
-          set -x
 
-          # NB: We are currently having an intermittent GPU-related issue on G5 runners with
-          # A10G GPU. Once this happens, trying to reset the GPU as done in setup-nvidia does
-          # not seem to help. Here are some symptoms:
-          #   * Calling nvidia-smi timeouts after 60 second
-          #   * Fail to run nvidia-smi with an unable to determine the device handle for GPU
-          #     unknown error
-          #   * Test fails with "No CUDA GPUs are available" error when initialize CUDA
-          #     in PyTorch
-          #   * Run docker --gpus all fails with error response from daemon while the command
-          #     nvidia-container-cli fails with detection error: nvml error: unknown error.
-          #
-          # As both the root cause and recovery path are unclear, let's take the runner out of
-          # service so that it doesn't get any more jobs
           UNRECOVERABLE_ERRORS=(
-            "No CUDA GPUs are available"
             "docker: Error response from daemon"
           )
 
