do not install lit, remove extra pip packages, do not use run.sh

diff --git a/.github/workflows/build-triton-rocm-wheel.yml b/.github/workflows/build-triton-rocm-wheel.yml
--- a/.github/workflows/build-triton-rocm-wheel.yml
+++ b/.github/workflows/build-triton-rocm-wheel.yml
@@ -52,23 +52,32 @@ jobs:
       - name: Build Triton ROCm wheel
         run: |
           set -x
+          mkdir -p "${RUNNER_TEMP}/artifacts/"
+          container_name=$(docker run \
+            --tty \
+            --detach \
+            -v "${GITHUB_WORKSPACE}:/pytorch" \
+            -v "${RUNNER_TEMP}/artifacts:/artifacts" \
+            -w /artifacts/ \
+            "${DOCKER_IMAGE}"      \
+          )
 
           # Determine python executable for given version
           case $PY_VERS in
           3.7)
-            PYTHON_BIN_PATH=/opt/python/cp37-cp37m/bin
+            PYTHON_EXECUTABLE=/opt/python/cp37-cp37m/bin/python
             ;;
           3.8)
-            PYTHON_BIN_PATH=/opt/python/cp38-cp38/bin
+            PYTHON_EXECUTABLE=/opt/python/cp38-cp38/bin/python
             ;;
           3.9)
-            PYTHON_BIN_PATH=/opt/python/cp39-cp39/bin
+            PYTHON_EXECUTABLE=/opt/python/cp39-cp39/bin/python
             ;;
           3.10)
-            PYTHON_BIN_PATH=/opt/python/cp310-cp310/bin
+            PYTHON_EXECUTABLE=/opt/python/cp310-cp310/bin/python
             ;;
           3.11)
-            PYTHON_BIN_PATH=/opt/python/cp311-cp311/bin
+            PYTHON_EXECUTABLE=/opt/python/cp311-cp311/bin/python
             ;;
           *)
             echo "Unsupported python version ${PY_VERS}"
@@ -76,27 +85,13 @@ jobs:
             ;;
           esac
 
-          # create run.sh to set python bin path
-          mkdir -p "${RUNNER_TEMP}/scripts/"
-          echo '#!/bin/bash' > "${RUNNER_TEMP}/scripts/run.sh"
-          echo "export PYTHON_BIN_PATH=${PYTHON_BIN_PATH}" >> "${RUNNER_TEMP}/scripts/run.sh"
-          echo 'export PATH=${PYTHON_BIN_PATH}:$PATH' >> "${RUNNER_TEMP}/scripts/run.sh"
-          echo '$@' >> "${RUNNER_TEMP}/scripts/run.sh"
-          chmod +x "${RUNNER_TEMP}/scripts/run.sh"
-
-          mkdir -p "${RUNNER_TEMP}/artifacts/"
-          container_name=$(docker run \
-            --tty \
-            --detach \
-            -v "${GITHUB_WORKSPACE}:/pytorch" \
-            -v "${RUNNER_TEMP}/artifacts:/artifacts" \
-            -v "${RUNNER_TEMP}/scripts:/scripts" \
-            -w /artifacts/ \
-            "${DOCKER_IMAGE}"      \
-          )
-
-          docker exec -t "${container_name}" /scripts/run.sh python -m pip install lit==15.0.7
-          docker exec -t "${container_name}" /scripts/run.sh python /pytorch/.github/scripts/build_triton_wheel.py --rocm
+          # rocm image had extra python pip packages that caused triton to fail to locate python3
+          # we uninstall each individually in case base image changes available packages
+          for package in cget click importlib-metadata meson ninja si typing-extensions zipp
+          do
+            docker exec -t "${container_name}" python -m pip uninstall -y ${package} || true
+          done
+          docker exec -t "${container_name}" "${PYTHON_EXECUTABLE}" /pytorch/.github/scripts/build_triton_wheel.py --rocm
           docker exec -t "${container_name}" chown -R 1000.1000 /artifacts
 
       - uses: actions/upload-artifact@v3
