removed conditionals to mi300 test

diff --git a/.github/workflows/connectivity-test.yaml b/.github/workflows/connectivity-test.yaml
--- a/.github/workflows/connectivity-test.yaml
+++ b/.github/workflows/connectivity-test.yaml
@@ -13,10 +13,19 @@ jobs:
         run: date
 
       - name: Wait for 3 hours
-        run: sleep 10800  # 3 hours in seconds
+        run: sleep 10  # 3 hours in seconds
 
       - name: Print end time
         run: date
 
       - name: Pass
         run: echo "Connectivity test passed — runner stayed alive for 3 hours."
+
+jobs:
+  crash-test:
+    runs-on: linux.rocm.gpu.mi300.2.test
+    steps:
+      - name: Intentional Failure
+        run: |
+          echo "This test is expected to fail."
+          exit 1
