Add more dependencies

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -20,7 +20,6 @@ jobs:
       docker-image-name: pytorch-linux-focal-linter
 
   lintrunner:
-    name: lintrunner
     needs: docker-image
     uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
     with:
@@ -52,65 +51,33 @@ jobs:
         exit $RC
 
   quick-checks:
-    name: quick-checks
-    runs-on: linux.20_04.4x
-    steps:
-      # [see note: pytorch repo ref]
-      - name: Checkout PyTorch
-        uses: pytorch/pytorch/.github/actions/checkout-pytorch@master
-        with:
-          submodules: false
-          fetch-depth: 1
-      - name: Clean PyTorch checkout
-        run: |
-          # Remove any artifacts from the previous checkouts
-          git clean -fxd
-      - name: Setup Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: '3.x'
-          architecture: x64
-          check-latest: false
-          cache: pip
-          cache-dependency-path: |
-            **/requirements.txt
-      - name: Install dependencies
-        uses: nick-fields/retry@v2.8.2
-        id: requirements
-        with:
-          timeout_minutes: 5
-          max_attempts: 3
-          retry_wait_seconds: 90
-          command: |
-            pip install -r requirements.txt --user
-            sudo apt-get install -y doxygen
-      - name: Ensure no non-breaking spaces (nonretryable)
-        if: always()
-        run: |
-          # NB: We use 'printf' below rather than '\u000a' since bash pre-4.2
-          # does not support the '\u000a' syntax (which is relevant for local linters)
-          (! git --no-pager grep -In "$(printf '\xC2\xA0')" -- . || (echo "The above lines have non-breaking spaces (U+00A0); please convert them to spaces (U+0020)"; false))
-      - name: Ensure cross-OS compatible file names (nonretryable)
-        if: always()
-        run: |
-          (! git ls-files | grep -E '([<>:"|?*]|[ .]$)' || (echo "The above file names are not valid across all operating systems. Please ensure they don't contain the characters '<>:""|?*' and don't end with a white space or a '.' "; false))
-      - name: Ensure no versionless Python shebangs (nonretryable)
-        if: always()
-        run: |
-          (! git --no-pager grep -In '#!.*python$' -- . || (echo "The above lines have versionless Python shebangs; please specify either python2 or python3"; false))
-      - name: C++ docs check (nonretryable)
-        if: ${{ always() && steps.requirements.outcome == 'success' }}
-        run: |
-          cd docs/cpp/source && ./check-doxygen.sh
-      - name: CUDA kernel launch check (nonretryable)
-        if: ${{ always() && steps.requirements.outcome == 'success' }}
-        run: |
-          set -eux
-          python torch/testing/_internal/check_kernel_launches.py |& tee "${GITHUB_WORKSPACE}"/cuda_kernel_launch_checks.txt
+    needs: docker-image
+    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
+    with:
+      runner: linux.2xlarge
+      docker-image: ${{ needs.docker-image.outputs.docker-image }}
+      script: |
+        # Ensure no non-breaking spaces
+        # NB: We use 'printf' below rather than '\u000a' since bash pre-4.2
+        # does not support the '\u000a' syntax (which is relevant for local linters)
+        (! git --no-pager grep -In "$(printf '\xC2\xA0')" -- . || (echo "The above lines have non-breaking spaces (U+00A0); please convert them to spaces (U+0020)"; false))
+
+        # Ensure cross-OS compatible file names
+        (! git ls-files | grep -E '([<>:"|?*]|[ .]$)' || (echo "The above file names are not valid across all operating systems. Please ensure they don't contain the characters '<>:""|?*' and don't end with a white space or a '.' "; false))
+
+        # Ensure no versionless Python shebangs
+        (! git --no-pager grep -In '#!.*python$' -- . || (echo "The above lines have versionless Python shebangs; please specify either python2 or python3"; false))
+
+        # C++ docs check
+        cd docs/cpp/source && ./check-doxygen.sh
+
+        # CUDA kernel launch check
+        set -eux
+        python3 torch/testing/_internal/check_kernel_launches.py |& tee "${GITHUB_WORKSPACE}"/cuda_kernel_launch_checks.txt
 
   pr-sanity-checks:
     name: pr-sanity-checks
-    runs-on: [self-hosted, linux.2xlarge]
+    runs-on: [self-hosted, linux.large]
     # Only run this on pull requests
     if: github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'skip-pr-sanity-checks')
     steps:
@@ -128,18 +95,14 @@ jobs:
           bash .github/scripts/pr-sanity-check.sh
 
   workflow-checks:
-    name: workflow-checks
     needs: docker-image
     uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
     with:
       runner: linux.2xlarge
       docker-image: ${{ needs.docker-image.outputs.docker-image }}
       script: |
-        set +e
         # Regenerate workflows
         .github/scripts/generate_ci_workflows.py
-        GENERATE_CI_WORKFLOW_RC=$?
-        set -e
 
         RC=0
         # Assert that regenerating the workflows didn't change them
@@ -157,9 +120,7 @@ jobs:
         fi
 
         # Check that jobs will be cancelled
-        if [[ "${GENERATE_CI_WORKFLOW_RC}" -eq 0 ]]; then
-          .github/scripts/ensure_actions_will_cancel.py
-        fi
+        .github/scripts/ensure_actions_will_cancel.py
 
         exit $RC
 
@@ -208,43 +169,15 @@ jobs:
   test-tools:
     name: Test tools
     if: ${{ github.repository == 'pytorch/pytorch' }}
-    runs-on: linux.20_04.4x
-    steps:
-      # [see note: pytorch repo ref]
-      # deep clone (fetch-depth 0) required, to allow us to use git log
-      - name: Checkout PyTorch
-        uses: pytorch/pytorch/.github/actions/checkout-pytorch@master
-        with:
-          submodules: false
-      - name: Setup Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: '3.8'
-          architecture: x64
-          check-latest: false
-          cache: pip
-          cache-dependency-path: |
-            **/requirements.txt
-            **/requirements-flake8.txt
-            **/.ci/docker/requirements-ci.txt
-            **/.github/requirements-gha-cache.txt
-      - name: Install dependencies
-        # mypy and boto3 versions copied from
-        # .ci/docker/common/install_conda.sh
-        run: |
-          set -eux
-          pip install -r requirements.txt
-          pip install boto3==1.19.12
-          pip install typing-extensions==3.10 --user
-          pip install -r requirements-flake8.txt --user
-          pip install rockset==1.0.3 --user
-          pip install -r requirements.txt --user
-          pip install mypy==0.960 --user
-          make setup_lint
-      - name: Test tools (nonretryable)
-        run: |
-          python3 -m unittest discover -vs tools/test -p 'test_*.py'
-          python3 -m unittest discover -vs .github/scripts -p 'test_*.py'
+    needs: docker-image
+    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
+    with:
+      runner: linux.2xlarge
+      docker-image: ${{ needs.docker-image.outputs.docker-image }}
+      script: |
+        # Test tools (nonretryable)
+        python3 -m unittest discover -vs tools/test -p 'test_*.py'
+        python3 -m unittest discover -vs .github/scripts -p 'test_*.py'
 
   test_collect_env:
     if: ${{ github.repository == 'pytorch/pytorch' }}
