ci: Clean up logic for `merge -r`
Rely on built in bash conditionals for doing the if statement rather
than relying on $?

Signed-off-by: Eli Uriegas <eliuriegas@meta.com>

[ghstack-poisoned]

diff --git a/.github/workflows/trymerge.yml b/.github/workflows/trymerge.yml
--- a/.github/workflows/trymerge.yml
+++ b/.github/workflows/trymerge.yml
@@ -45,8 +45,8 @@ jobs:
         run: |
           set -x
           if [ -n "${REBASE}" ]; then
-            python3 .github/scripts/tryrebase.py "${PR_NUM}" --branch "${REBASE}"
-            if [ $? != 1 ]; then
+            # attempt to rebase, if it fails then comment on the PR that it failed
+            if ! python3 .github/scripts/tryrebase.py "${PR_NUM}" --branch "${REBASE}"; then
               python3 .github/scripts/comment_on_pr.py "${PR_NUM}" "merge"
               exit 0
             fi
