undo test

diff --git a/.github/workflows/update-viablestrict.yml b/.github/workflows/update-viablestrict.yml
--- a/.github/workflows/update-viablestrict.yml
+++ b/.github/workflows/update-viablestrict.yml
@@ -4,7 +4,6 @@ on:
   schedule:
     - cron: 17,47 * * * *
   workflow_dispatch:
-  push:
 
 concurrency:
   group: ${{ github.workflow }}
@@ -44,14 +43,14 @@ jobs:
           echo "latest_viable_sha=$output" >> "${GITHUB_OUTPUT}"
         id: get-latest-commit
 
-      # - name: Push SHA to viable/strict branch
-      #   if: steps.get-latest-commit.outputs.latest_viable_sha != 'None'
-      #   env:
-      #     GITHUB_TOKEN: ${{ secrets.MERGEBOT_TOKEN }}
-      #   run: |
-      #     git config --global user.email "pytorchmergebot@users.noreply.github.com"
-      #     git config --global user.name "PyTorch MergeBot"
-      #     echo "Set the latest sha variable to be ${{ steps.get-latest-commit.outputs.latest_viable_sha }}"
-      #     # Pushing an older green commit here will fail because it's non-fast-forward, which is ok
-      #     # to ignore because we already have the later green commit in visable/strict
-      #     git push origin "${{ steps.get-latest-commit.outputs.latest_viable_sha }}":viable/strict || true
+      - name: Push SHA to viable/strict branch
+        if: steps.get-latest-commit.outputs.latest_viable_sha != 'None'
+        env:
+          GITHUB_TOKEN: ${{ secrets.MERGEBOT_TOKEN }}
+        run: |
+          git config --global user.email "pytorchmergebot@users.noreply.github.com"
+          git config --global user.name "PyTorch MergeBot"
+          echo "Set the latest sha variable to be ${{ steps.get-latest-commit.outputs.latest_viable_sha }}"
+          # Pushing an older green commit here will fail because it's non-fast-forward, which is ok
+          # to ignore because we already have the later green commit in visable/strict
+          git push origin "${{ steps.get-latest-commit.outputs.latest_viable_sha }}":viable/strict || true
