relax ROCm GHA 2- or 4-GPU restriction to >=2

diff --git a/.github/templates/common.yml.j2 b/.github/templates/common.yml.j2
--- a/.github/templates/common.yml.j2
+++ b/.github/templates/common.yml.j2
@@ -77,13 +77,15 @@ concurrency:
         if: always()
         run: |
           ngpu=$(rocminfo | grep -c -E 'Name:.*\sgfx')
-          if [[ "x$ngpu" != "x2" && "x$ngpu" != "x4" ]]; then
-              if [[ $ngpu -eq 0 ]]; then
-                echo "Error: Failed to detect any GPUs on the runner"
-              else
-                echo "Error: Detected $ngpu GPUs on the runner, when only 2 or 4 were expected"
-              fi
-              echo "Please file an issue on pytorch/pytorch reporting the faulty runner. Include a link to the runner logs so the runner can be identified"
+          msg="Please file an issue on pytorch/pytorch reporting the faulty runner. Include a link to the runner logs so the runner can be identified"
+          if [[ $ngpu -eq 0 ]]; then
+              echo "Error: Failed to detect any GPUs on the runner"
+              echo "$msg"
+              exit 1
+          fi
+          if [[ $ngpu -eq 1 ]]; then
+              echo "Error: only 1 GPU detected, at least 2 GPUs are needed for distributed jobs"
+              echo "$msg"
               exit 1
           fi
       - name: Runner health check disconnect on failure
