simplify rocm runner health check

diff --git a/.github/templates/common.yml.j2 b/.github/templates/common.yml.j2
--- a/.github/templates/common.yml.j2
+++ b/.github/templates/common.yml.j2
@@ -109,30 +109,21 @@ concurrency:
           rm -f ~/.ssh/authorized_keys
       - name: Set DOCKER_HOST
         run: echo "DOCKER_HOST=unix:///run/user/$(id -u)/docker.sock" >> "${GITHUB_ENV}"
-      - name: Runner System Information
+      - name: Runner health check
         run: |
           cat /etc/os-release || true
           cat /etc/apt/sources.list || true
           cat /etc/apt/sources.list.d/rocm.list || true
           cat /opt/rocm/.info/version || true
           whoami
-      - name: rocm-smi
-        run: |
           rocm-smi
-      - name: rocminfo
-        run: |
           rocminfo
-      - name: GPU count
-        id: ngpu
-        run: |
-          echo "::set-output name=result::$(rocminfo | grep -E 'Name:.*\sgfx' | wc -l)"
-      - name: Ensure all 4 GPUs available
-        if: ${{ steps.ngpu.result != 4 }}
-        uses: actions/github-script@v3
-        with:
-          script: |
-            core.setFailed('Failed to detect 4 GPUs')
-      - name: Health check failure step
+          ngpu=$(rocminfo | grep -c -E 'Name:.*\sgfx')
+          if [[ "x$ngpu" != "x4" ]]; then
+              echo "Failed to detect 4 GPUs on the runner"
+              exit 1
+          fi
+      - name: Runner health check disconnect on failure
         if: ${{ failure() }}
         run: |
           killall runsvc.sh
