move env to job

diff --git a/.github/templates/common.yml.j2 b/.github/templates/common.yml.j2
--- a/.github/templates/common.yml.j2
+++ b/.github/templates/common.yml.j2
@@ -8,7 +8,12 @@
 
 {%- macro concurrency(build_environment) -%}
 concurrency:
-  group: !{{ build_environment }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
+  {#- Explanation of the ciflow check: ciflow-triggered workflows use the push
+  event. If we just use `github.sha` as the concurrency key, each push will get
+  its own concurrency group. We want the behavior that new pushes of the ciflow
+  tag to invalidate old ones, so we use the ciflow tag ref name as the key
+  instead of the sha. #}
+  group: !{{ build_environment }}-${{ github.event.pull_request.number || (startsWith(github.ref_name, 'ciflow') && github.ref_name || github.sha) }}-${{ github.event_name == 'workflow_dispatch' }}
   cancel-in-progress: true
 {%- endmacro -%}
 
@@ -118,12 +123,12 @@ concurrency:
           submodules: !{{ submodules }}
 {%- endmacro -%}
 
-{%- macro upload_downloaded_files(name, artifact_name="", use_s3=True, when="always()") -%}
+{%- macro upload_downloaded_files(name, config=None, shard=None, num_shards=None, runner=None, artifact_name="", use_s3=True, when="always()") -%}
       - name: Zip JSONs for upload
         if: !{{ when }}
         env:
 {%- if name == 'linux' or name == 'windows' or name == 'macos' %}
-          FILE_SUFFIX: '${{ github.job }}-${{ matrix.config }}-${{ matrix.shard }}-${{ matrix.num_shards }}-${{ matrix.runner }}'
+          FILE_SUFFIX: '${{ github.job }}-!{{ config }}-!{{ shard }}-!{{ num_shards }}-!{{ runner }}'
 {%- else %}
           FILE_SUFFIX: '!{{ name }}-${{ github.job }}'
 {%- endif %}
@@ -156,12 +161,12 @@ concurrency:
             test-jsons-*.zip
 {%- endmacro -%}
 
-{%- macro upload_test_reports(name, artifact_name="", use_s3=True) -%}
+{%- macro upload_test_reports(name, config=None, shard=None, num_shards=None, runner=None, artifact_name="", use_s3=True) -%}
       - name: Zip test reports for upload
         if: always()
         env:
 {%- if name == 'linux' or name == 'windows' or name == 'macos' %}
-          FILE_SUFFIX: '${{ github.job }}-${{ matrix.config }}-${{ matrix.shard }}-${{ matrix.num_shards }}-${{ matrix.runner }}'
+          FILE_SUFFIX: '${{ github.job }}-!{{ config }}-!{{ shard }}-!{{ num_shards }}-!{{ runner }}'
 {%- else %}
           FILE_SUFFIX: '!{{ name }}-${{ github.job }}'
 {%- endif %}
@@ -208,22 +213,6 @@ concurrency:
           PYTHONIOENCODING: "utf-8"
         run: |
           python3 tools/render_junit.py test/
-{%- endmacro -%}
-
-{%- macro ciflow_should_run_job(ciflow_config) %}
-  !{{ ciflow_config.root_job_name }}:
-    runs-on: linux.large
-    timeout-minutes: !{{ timeout_minutes }}
-    env:
-      IS_PROBOT_TRIGGER_EVENT: ${{ (github.event.action == '!{{ ciflow_config.trigger_action }}') && (github.event.assigneed.login == '!{{ ciflow_config.trigger_actor }}') }}
-      LABEL_CONDITIONS: ${{ !{{ ciflow_config.label_conditions }} }}
-      LABELS: ${{ toJson(github.event.pull_request.labels.*.name) }}
-    if: !{{ ciflow_config.root_job_condition }}
-    steps:
-      - name: noop
-        run: echo running !{{ ciflow_config.root_job_name }}
-      - name: print labels
-        run: echo "${LABELS}"
 {%- endmacro -%}
 
 {%- macro calculate_docker_image(always_rebuild) -%}
@@ -289,7 +278,101 @@ concurrency:
 
 {%- macro set_xcode_version(xcode_version) -%}
 {%- if xcode_version != '' %}
-  # Set xcode xcode version to !{{ xcode_version }}
-  DEVELOPER_DIR: /Applications/Xcode_!{{ xcode_version }}.app/Contents/Developer
+      # Set xcode xcode version to !{{ xcode_version }}
+      DEVELOPER_DIR: /Applications/Xcode_!{{ xcode_version }}.app/Contents/Developer
 {%- endif %}
+{%- endmacro -%}
+
+{%- macro win_wait_and_kill_ssh() -%}
+      - name: Wait until all sessions have drained
+        shell: powershell
+        if: always()
+        timeout-minutes: 120
+        run: |
+          .github\scripts\wait_for_ssh_to_drain.ps1
+      - name: Kill active ssh sessions if still around (Useful if workflow was cancelled)
+        shell: powershell
+        if: always()
+        run: |
+          .github\scripts\kill_active_ssh_sessions.ps1
+{%- endmacro %}
+
+{%- macro upload_android_binary_size(build_type, artifacts) -%}
+      - name: Display and upload binary build size statistics (Click Me)
+        # temporary hack: set CIRCLE_* vars, until we update
+        # tools/stats/print_test_stats.py to natively support GitHub Actions
+        env:
+          AWS_DEFAULT_REGION: us-east-1
+          SCRIBE_GRAPHQL_ACCESS_TOKEN: ${{ secrets.SCRIBE_GRAPHQL_ACCESS_TOKEN }}
+          BRANCH: ${{ steps.parse-ref.outputs.branch }}
+          PR_NUMBER: ${{ github.event.pull_request.number }}
+          SHA1: ${{ github.event.pull_request.head.sha || github.sha }}
+          TAG: ${{ steps.parse-ref.outputs.tag }}
+          WORKFLOW_ID: '${{ github.run_id }}_${{ github.run_number }}'
+        run: |
+          # The artifact file is created inside docker container, which contains the result binaries.
+          # Now unpackage it into the project folder. The subsequent script will scan project folder
+          # to locate result binaries and report their sizes.
+          # If artifact file is not provided it assumes that the project folder has been mounted in
+          # the docker during build and already contains the result binaries, so this step can be skipped.
+          export ARTIFACTS=!{{ artifacts }}
+          if [ -n "${ARTIFACTS}" ]; then
+            tar xf "${ARTIFACTS}" -C "${GITHUB_WORKSPACE}"
+            cd "${GITHUB_WORKSPACE}"
+          fi
+          COMMIT_TIME=$(git log --max-count=1 --format=%ct || echo 0)
+          export COMMIT_TIME
+          ANDROID_BUILD_TYPE=!{{ build_type}}
+          export ANDROID_BUILD_TYPE
+          pip3 install requests==2.26 boto3==1.16.34
+          python3 -m tools.stats.upload_binary_size_to_scuba "android" || exit 0
+{%- endmacro -%}
+
+{%- macro build_android(env_name, container_suffix) -%}
+      - name: Build-!{{ container_suffix }}
+        env:
+          BRANCH: ${{ steps.parse-ref.outputs.branch }}
+        run: |
+          # detached container should get cleaned up by teardown_ec2_linux
+          #!/bin/bash -eo pipefail
+          # Pull Docker image and run build
+          time docker pull "${DOCKER_IMAGE}" >/dev/null
+          echo "${DOCKER_IMAGE}"
+          export container_name
+          container_name=$(docker run \
+            -e BUILD_ENVIRONMENT=!{{ env_name }} \
+            -e JOB_BASE_NAME \
+            -e MAX_JOBS="$(nproc --ignore=2)" \
+            -e AWS_DEFAULT_REGION \
+            -e IS_GHA \
+            -e PR_NUMBER \
+            -e SHA1 \
+            -e BRANCH \
+            -e GITHUB_RUN_ID \
+            -e SCCACHE_BUCKET \
+            -e XLA_CLANG_CACHE_S3_BUCKET_NAME \
+            -e CUSTOM_TEST_ARTIFACT_BUILD_DIR \
+            -e SKIP_SCCACHE_INITIALIZATION=1 \
+            -e TORCH_CUDA_ARCH_LIST \
+            -e PR_LABELS \
+            -e http_proxy="!{{ squid_proxy }}" -e https_proxy="!{{ squid_proxy }}" -e no_proxy="!{{ squid_no_proxy }}" \
+            --env-file="/tmp/github_env_${GITHUB_RUN_ID}" \
+            --security-opt seccomp=unconfined \
+            --cap-add=SYS_PTRACE \
+            --tty \
+            --detach \
+            --user jenkins \
+            -w /var/lib/jenkins/workspace \
+            "${DOCKER_IMAGE}"
+          )
+          git submodule sync && git submodule update -q --init --recursive --depth 1 --jobs 0
+          docker cp "${GITHUB_WORKSPACE}/." "${container_name}:/var/lib/jenkins/workspace"
+          # shellcheck disable=SC1105
+          ((echo "sudo chown -R jenkins . && .jenkins/pytorch/build.sh && find ${BUILD_ROOT} -type f -name "*.a" -or -name "*.o" -delete") | docker exec -u jenkins -i "${container_name}" bash) 2>&1
+
+          # Copy dist folder back
+          export COMMIT_DOCKER_IMAGE=${DOCKER_IMAGE}-!{{ container_suffix }}
+          docker cp "${container_name}:/var/lib/jenkins/workspace/dist" "${GITHUB_WORKSPACE}/." || echo "Dist folder not found"
+          docker commit "${container_name}" "${COMMIT_DOCKER_IMAGE}"
+          time docker push "${COMMIT_DOCKER_IMAGE}"
 {%- endmacro -%}
